name: Prettier Test

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}  

    - name: Prettify code
      #ses: creyD/prettier_action@87e1553a825c17f83a666a2fa0f4320c8e39c984
      #uses: fsz-codeshop/prettier_action@issue-37-dry-run-reporting-unpretty
      uses: fsz-codeshop/prettier_action@debug
      with:
        prettier_options: --write **/*.js
        dry: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
